### ISSUE TITLE
Weird problem while compiling service.jar

### ISSUE THREAD

**Issue by dogaoz** [MiCode/patchrom_miui#17]
doga@doga-Inspiron-N5110 /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/DogaOz_$ make fullota

> > > build out/framework-miui-res.apk...
> > > /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/tools/apktool --quiet d -f /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/miui/XHDPI/system/framework/framework-miui-res.apk out/framework-miui-res
> > > ls: cannot access overlay/framework-miui-res/res/[^v]_: No such file or directory
> > > WARING[CHECK]: No xml file in overlay/framework-miui-res/res/values
> > > /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
> > > <<< build out/framework-miui-res.apk completed!
> > > /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/tools/apktool --quiet d -f /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/miui/XHDPI/system/framework/services.jar out/services_miui
> > > build out/services.jar...
> > > /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/tools/add_miui_smail.sh >/dev/null out/services_miui out/services
> > > /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/tools/apktool --quiet b out/services out/services.jar
> > > [0,0] No enum const class org.jf.dexlib.AnnotationVisibility.BUİLD
> > > Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: /media/doga/ddb7cb40-dcf0-4f1a-93e4-1cc10d761ea6/MIUI-4.1_2-JELLYBEAN/DogaOz_i9500/out/services/smali/com/android/server/ConnectivityService.smali
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
> > >     at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:66)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
> > >     at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:257)
> > >     at brut.androlib.Androlib.buildSources(Androlib.java:214)
> > >     at brut.androlib.Androlib.build(Androlib.java:205)
> > >     at brut.androlib.Androlib.build(Androlib.java:176)
> > >     at brut.apktool.Main.cmdBuild(Main.java:228)
> > >     at brut.apktool.Main.main(Main.java:79)
> > > make: *_\* [out/services.jar] Hata 1

**Comment by zdunex25** [comment]
ConnectivityService.smali - it might be even one spacebar in wrong line/place that will bring such error

**Comment by dogaoz** [comment]
i fixed that :) btw : how should i separate framework.jar .. i'm getting method index is too large problem.. also framework2.jar is too big too :) i cant move some files into framework2.jar

**Comment by zdunex25** [comment]
Is it even possible to to have 'em both too large :P ??
I believe that you could create a separate method for framework3.jar, but you would need to add it to bootclass (kernel) and create proper preloaded-classes framework3's addon.. never tried just guessing.

**Comment by dogaoz** [comment]
i'm using touchwiz rom as base ...because i9500 doesnt have stable device-tree..but framework3 doesnt exist normally. so i cant create framework3 .. i can create dex file but i cant create jar file for that .. always i'm getting problems on boot. yeah i added bootclasspath too..

**Comment by zdunex25** [comment]
I mean you create it yourself.. just like google did once framework.jar started to be too large, add some smart code.

**Comment by ghost** [comment]
How did you solve that?
