### ISSUE TITLE
Brand New Email 

### ISSUE THREAD

**Issue by zdunex25** [MiCode/patchrom_miui#21]
So you guys did not test it yet I guess, make fullota crashes at some point:

/home/z25/patchromv542/tools/apktool --quiet d -t miui -f /home/z25/patchromv542/miui/XHDPI/system/app/Email.apk out/Email
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101045f
    at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:61)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:35)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:313)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:130)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:34)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:238)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:115)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
    at brut.apktool.Main.cmdDecode(Main.java:146)
    at brut.apktool.Main.main(Main.java:77)
make: **\* [out/Email] Error 1

**Comment by nian0114** [comment]
Please dont modify Email.apk
They changed Email.apk

**Comment by zdunex25** [comment]
How are we supposed to translate it now?

**Comment by nian0114** [comment]
I don't translate this app. 

发自我的 iPhone

**Comment by zdunex25** [comment]
Mi3's one is decompileable I will use that one..

**Comment by zdunex25** [comment]
Well, loading nexus 5's framework resources fixing the issue.
